### ISSUE TITLE
feat: rule configuration file spec

### ISSUE THREAD

**Issue by pozil** [Force-Config-Control/lightning-flow-scanner-cli#19]
I have a bunch of comments on the structure of the "rule ignore" file. I will leave them here so that they remain visible in the project although they could be split in multiple issues.

I based my assumptions based on the [flows.scanignore.json](https://github.com/Force-Config-Control/lightning-flow-scanner-example-flows/blob/c3fff86dda289544dea3ef03587a45bdd965e5a8/flows.scanignore.json) file from the example repo. Let me know if this isn't the right format.

**Suggestions:**
1. rename file to something like `.flow-scan-ignore` to align with what others tools like Prettier or ESlint do (hidden file that starts with `.` and no file extension)
1. shorten property names. Ex: `flowsToBeIgnored` -> `ignoredFlows`, `rulesToBeIgnoredInFlows` -> `ignoredRulesInFlows`
1. be consistent in property case format: if you go for camelcase, stick to it. Ex: `flowname` -> `flowName`, `rulename` -> `ruleName`
1. I would recommend a rule configuration format [similar to ESLint](https://eslint.org/docs/user-guide/configuring/rules) to ease future evolution. For example, right now, you only have active or inactive rules but later on, you may need three states: off, warning and error. Also, you might want to establish some project-wide rules and fine tune with overrides for specific flows.

Here's a JSON example of what this could look like:
```json
{
    "rules": {
        "rule1": "error",
        "rule2": "off"
    },
    "overrides": [
        {
            "flowName": "myFlow1",
            "rules": {
                "rule1": "off"
            }
        }
    ]
}
```

**Comment by RubenHalman** [comment]
@pozil I deviated a little from what you suggested but can see how all comments are relevant for the future and am very thankful for your input. You can find the new [.flowscanignore](https://github.com/Force-Config-Control/lightning-flow-scanner-example-flows/blob/master/.flowscanignore) file included in the example repository but it looks as such:

```
{
  "activeRules": [
    "DMLStatementInLoop",
    "DuplicateDMLOperationsByNavigation",
    "HardcodedIds"
  ],
  "overrides": [
      {
          "flowName": "Create Property",
          "results": [{
              "ruleName" : "DuplicateDMLOperationsByNavigation",
              "result":"error_creating_records"
          },
          {
            "ruleName" : "DuplicateDMLOperationsByNavigation",
            "result":"upload_picture"
        }]
      }
  ]
}
```

**Regarding the rule settings:**
I decided to go with making it possible to specify the rules to be ran in the file, rather than individual rule configurations as there is some additional ease of use: new rules will be automatically included if you don't specify any, lowering the bar to get everything up and running for a test run. I can see how your proposal perhaps makes sense in the future, but for now the scan doesn't support different levels of warnings and I want to keep the configurations as simple as possible.

**Regarding the overrides:**
I decided to make overrides based on a result, instead of rules. This allows to ignore each results individually and thus support all possible scenarios. I am still thinking on how and if overrides should be by flow or rule too.(hopefully people strive to be as precise as possible on exemptions).

Once again, thank you very much. I will be shortly releasing the changes and am keen for any further input you might have. 

Kind regards,
